### PR TITLE
PHP 7.4 compatibility change

### PR DESCRIPTION
**Pull request by coffeemedia**
Prevent notice:
`Notice: Trying to access array offset on value of type null in .../vendor/spipu/html2pdf/src/Html2Pdf`

### CODE REVIEW

**Comment by Ousret** [comment]
Thank you. I can confirm it does work for me. (PHP 7.4)

**Comment by spipu** [comment]
Thanks a lot, i will merge it ! 
can you just add a line on https://github.com/spipu/html2pdf/blob/master/CHANGELOG.md on the unrelease part ?

**Comment by spipu** [comment]
hum, there is a conflict :( could you resolve it ? i will accept the MR just after :)

**Comment by coffeemedia** [comment]
It has been resolved and checks are passing. Thank you for your quick response!

**Comment by spipu** [comment]
it tells me "This branch cannot be rebased due to conflicts" :(

**Comment by spipu** [comment]
done !

**Comment by mewejo** [comment]
Can this be tagged as a release/versioned please? :)

**Comment by Ousret** [comment]
would be great.

**Comment by spipu** [comment]
v5.2.2 released !

**Comment by A-JBotero** [comment]
how can i solve this


Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\sim\pdf\_tcpdf_5.0.002\tcpdf.php on line 3018

Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\sim\pdf\_tcpdf_5.0.002\tcpdf.php on line 3018

Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\sim\pdf\_tcpdf_5.0.002\tcpdf.php on line 3018
TCPDF ERROR: Some data has already been output, can't send PDF file

	$this->SetFont($this->footer_font[0], $this->footer_font[1], $this->footer_font[2]);

**Pull request merged**
