### PR TITLE
Feature/qrcode data matrix

### PR DESCRIPTION
**Pull request by Pierozi**
Hello,

I've meet couples troubles for generate a barecode with the type DATAMATRIX.
because the method only let QRCODE type forwarded to tcpdf.

after look at the code i've made a little patch for authorize all the type input going through tcpdf argument type. (maybe we can add couples checker for sure type are handle)

but let DATAMATRIX type are not the only change required, because the method `prepareTxt` replace spaces and alterate the barecode render. I've add add an attribute `rawvalue` on tag for let user disable the `prepareTxt` method.

Let me know if this is acceptable for you, and what change you would like.
i've made the PR from master, but i'm bit lost with the new change under 4.5/4.6 maybe better to made it from theses version branches ?

I've also a branch example with only the example without change in code.

https://github.com/Power-LAB/html2pdf/tree/examples/gls-qrcode-datamatrix

### CODE REVIEW

**Comment by Pierozi** [comment]
I've just made a change 2217814 with an extra parameter on prepareTxt for trim the value.
because the default trim on value alter the barecode render.

**Comment by spipu** [comment]
hi,

the QRCODE tag is only for QRCODE.

to manage others 2D bar code, you can use the BARCODE tag, with the attribute dimension="2D" (in the last version of the master branch)

The example is very very big, with binary file, is it possible to have lighter example ?

thanks,

**Comment by Pierozi** [comment]
Hello there,

It's been a while since I write this code.
I don't know if the BARCODE works well now.
But last year, it wasn't for barcode or QR code.
The mutation in prepareTxt method is the main goal of my PR, the `rawvalue` attribute is important for not corrupt the render.

The example is not so big, just a few FONTS requirement for have real GLS DATAMATRIX render.
Like you have others example is the project, I don't understand why it's an issue?

**Comment by Pierozi** [comment]
If you are still ok to implement this kind of `DATAMATRIX` I will rebase my fork and test with recent change.

**Comment by spipu** [comment]
why not, but by  using the BARCODE tag, with the attribute dimension="2D", not the QRCODE tag.

**Comment by Pierozi** [comment]
You didn't understand that the dimension 2D does not support the GLS DATAMATRIX.
But anyway, this integration is there from long time now.

**Pull request closed without merging**
