### PR TITLE
Update 4.05

### PR DESCRIPTION
**Pull request by LittleBigFox**
TCPDF 6.2.11
END_LAST_PAGE tag

### CODE REVIEW

**Comment by spipu** [comment]
Are you sure you have test all the functionalities, because since the v6.0.0 of TCPDF, some modifications are not compatible directly with HTML2PDF (see the TCPDF changelog). That's why i never do this upgrade : it takes time to test and modify HTML2PDF.

About the tcpdf example folder, it is better to clean it to have a project with less file (see https://github.com/spipu/html2pdf/tree/master/_tcpdf_5.0.002/doc)

**Comment by LittleBigFox** [comment]
Hi Spipu!

I use your project from a long time, so first, thank you for your work!

I've test it with table tag, img tag, ul, li, and many more, and the output is quite similar to v4.04, but i suppose there some functions than i've not tested.

I only made one change for TCPDF, in parsingCss class, for webcolor.

So please ignore my pull, i'm gonna test it more, and try to resolve my 2 issues before request.

**Comment by LittleBigFox** [comment]
I replaced tabs by whitespaces.

**Comment by spipu** [comment]
Thks for tab ;)

For the upgrade of TCPDF, about "I only made one change for TCPDF, in parsingCss class, for webcolor.", i did not find it  in the merge request (that was one of the point why i was telling  "Are you sure you have test all the functionalities"). Have you forgot to put it ?

about the END_LAST_PAGE tag maybe can you create a specific merge request on another branch on your side  for this point, so you can separate the TCPDF upgrade from you others devs on this project ?

Thanks for your help,

Laurent

**Comment by LittleBigFox** [comment]
Oups sorry, i'm a beginner with Git tools ^^ I've just reupload this file.

But you are right, i just test your example folder, some file doesn't give output, so i'm gonna investigate on it. With my excuses!

I'm gonna try to do a specific merge for END_LAST_PAGE tag, first,

**Pull request closed without merging**
