### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by kstenschke**
These are a few simple performance improvements, without any functional change to html2pdf's functionality. For details see included commits.

### CODE REVIEW

**Comment by spipu** [comment]
Hi,

could you rebase your branche ? thanks !

**Comment by divinity76** [comment]
on  that same note, theres lot of places in the code where the post-increment operator should be replaced with pre-increment operator. pre-increment is pretty much always faster, in every language. it uses fewer opcodes than post-increment, and the `old` value is not returned, only the new value, so we don't need 2 values (old value AND new value, as the post-increment does), etc. note that in C/C++, you need to compile with -O0 (`do not optimize the code`)  to actually see any difference, else the compiler will auto optimize it... but PHP does not auto-optimize it.

 proof that the pre-increment operator is faster in PHP:

```php
<?php 
for($i=0;$i<100000000;++$i){
	//heating up the cpu (if it uses some power saving feature or whatever)
}
$i=0;
$PreIncrementStart=microtime(true);
for($i=0;$i<100000000;++$i){
	//counting to 100 million, using pre-increment.
}
$PreIncrementEnd=microtime(true);
$i=0;
$PostIncrementStart=microtime(true);
for($i=0;$i<100000000;$i++){
	//counting to 100 million, using post-increment.
}
$PostIncrementEnd=microtime(true);
$PreTime=$PreIncrementEnd-$PreIncrementStart;
$PostTime=$PostIncrementEnd-$PostIncrementStart;
if($PreTime<$PostTime){
	echo "the fastest was pre-increment. (which totally makes sense, it's consistent with c/c++, and it uses fewer opcodes than the post-increment, and the `old` value is not returned, only the new value, so we don't need 2 values (old value AND new value, as the post-increment does)..)";
} else {
	echo "the fastest was post-increment... i am very surprised.";
}
echo "the difference was: ".abs($PreTime-$PostTime)." seconds.";
```

**Comment by spipu** [comment]
Hi, and sorry  for the delay.
Could you rebase your PR ?

**Comment by spipu** [comment]
Finally, do not rebase it. I will do the work myself, thanks for all the improvements !

**Pull request closed without merging**
