### PR TITLE
Add intregration with travis and improve phpunit.xml config file

### PR DESCRIPTION
**Pull request by fagundes**
issue #37 

This PR is really two suggestions.

First, move tests to `test` folder. Because we can separate main code from test code and it's a common pratice.

Second, add travis file. So we can integrate with it. Every time some push or pull request. All tests cases will run again, to check if the new commits added or not some error. 

I added a commit to fix some code style. ;)

### CODE REVIEW

**Comment by fagundes** [comment]
If someone want to read more about [travis](https://travis-ci.org/).

I also added temporarily travis at my [htmpl2pdf fork](https://travis-ci.org/fagundes/html2pdf).

**Comment by juchi** [comment]
I agree about travis linkage, this is definitely needed, a well a some code quality tool like scrutinizer.

However, I personaly don't like moving the tests into a test folder next to the src. This is the Zend way of doing it but I prefer Symfony's, because the namespaces are isolated and we only need one declaration inside the autoloader.

Concerning the travis configuration file, I would like to add the tests on php 5.6 and remove the allowed failures on PHP 5.x version, as the library should be working for those systems.

**Comment by fagundes** [comment]
Ok! I can git squash this PR, and remove the first commit and update the second.

**Comment by spipu** [comment]
Ok for me to have the test folder in the src folder.

Is it done ? I have a pb and can not see the changes :(

**Comment by fagundes** [comment]
Yes. I have changed the commits. I didn't move the tests, added the travis file (you guys need to add this repository into travis) and I updated the travis file like @juchi ask to do. I also improved phpunit.xml file to have colors.

**Pull request merged**
