### PR TITLE
Page break Support via DIV-Element

### PR DESCRIPTION
**Pull request by dennisheiden**
Issue:
https://github.com/spipu/html2pdf/issues/143

Solution (Thanh Trungs answer):
https://stackoverflow.com/questions/2117788/page-break-in-html2pdf

How to use:
` <div style="page-break-after:always;"></div>`

### CODE REVIEW

**Comment by dennisheiden** [comment]
Because you loose the header and footer on the second page if you close the page.
With the div-based solution you are keeping header and footer document wide after a page break.

**Comment by spipu** [comment]
no, you don't, if you use page_set="old"

http://wiki.spipu.net/doku.php?id=html2pdf:en:v4:page

**Comment by dennisheiden** [comment]
Ok, I am loosing the margins now:
```
<page  backtop="35mm" backbottom="35mm" backleft="0mm" backright="1mm"  pageset="old" >
...
test</page><page pageset="old">test2

....
</page>
```

**Comment by dennisheiden** [comment]
Ok, I am loosing the margins now:
```
<page  backtop="35mm" backbottom="35mm" backleft="0mm" backright="1mm"  pageset="old" >
...
test</page><page pageset="old">test2

....
</page>
```

**Comment by spipu** [comment]
could you rebase and update the changelog file ?

thanks

**Comment by LittleBigFox** [comment]
Hi! I've change this for page-break-after and before too... Because i need :)

**Comment by spipu** [comment]
added in the last commit :) i close

**Comment by dennisheiden** [comment]
Hi spipu, sorry that I wasn't able to rebasing and updating the changelog. Thank you for your commit.

**Pull request closed without merging**
